# ============================================================================
#  SPDX-License-Identifier: UPL-1.0
#
#  Copyright (c) 2026 Chase Allen Ringquist
#
#  This file is part of an operating system, software, and network Work
#  conceived and authored by Chase Allen Ringquist. The Author retains
#  copyright and authorship. Use of this file is licensed as follows.
#
#  ----------------------------------------------------------------------------
#  The Universal Permissive License (UPL), Version 1.0
#
#  Subject to the condition set forth below, permission is hereby granted to
#  any person obtaining a copy of this software, associated documentation
#  and/or data (collectively the "Software"), free of charge and under any
#  and all copyright rights in the Software, and any and all patent rights
#  owned or freely licensable by each licensor hereunder covering either
#  (i) the unmodified Software as contributed to or provided by such
#  licensor, or (ii) the Larger Works (as defined below), to deal in both
#
#  (a) the Software, and
#
#  (b) any piece of software and/or hardware listed in the lrgrwrks.txt file
#  if one is included with the Software (each a "Larger Work" to which the
#  Software is contributed by such licensors),
#
#  without restriction, including without limitation the rights to copy,
#  create derivative works of, display, perform, and distribute the Software
#  and make, use, sell, offer for sale, import, export, have made, and have
#  sold the Software and the Larger Work(s), and to sublicense the foregoing
#  rights on either these or other terms.
#
#  This license is subject to the following condition:
#
#  The above copyright notice and either this complete permission notice or
#  at a minimum a reference to the UPL must be included in all copies or
#  substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.
#  ----------------------------------------------------------------------------
#
#  Do not remove or alter this notice or any record of origin.
#  See NOTICE.md in the project root for authorship and ownership terms.
#
#  Contact:  ringquistchase@gmail.com  |  (918) 845-0940
#            Bixby, OK, United States
# ============================================================================

"""
remission_core.py
=================
Computational "cancer -> modeled reference match" workflow: sequence
comparison, 2-bit binary DNA encoding, a string-level CRISPR edit MODEL,
post-edit verification, longitudinal follow-up comparison, and a
hash-linked ledger of every stage.

This single file runs in two places without changes:
  - On the host (CPython 3), imported by remission_workflow.py.
  - As a MicroPython task bundle for the Network OS kernel
    (os/tasks/remission/REMISSION.PY, generated by
    build_task_bundles.py). It therefore uses only json, hashlib,
    binascii and sys, and avoids CPython-only APIs such as
    hashlib.hexdigest(), json.dumps(sort_keys=...), dataclasses and typing.

What this is NOT:
  - The CRISPR step is a string transformation, not guide-RNA design, a
    delivery protocol, a laboratory procedure or a biological genome edit.
  - MODELED_REFERENCE_MATCH means the modeled string equals the reference.
    It never implies CLINICALLY_CONFIRMED_REMISSION; that status is only
    ever copied from externally supplied clinical evidence.

Privacy: the ledger holds only SHA-256 digests. Full records (which
contain sequences) are returned separately so the host can store them
encrypted off-chain; they are never meant for an immutable chain.
"""

import binascii
import hashlib
import json
import sys

SCHEMA = "remission-model.v1"
MAX_BASES = 4096
MAX_FOLLOW_UPS = 16
MAX_INPUT_BYTES = 262144
GENESIS_HASH = "0" * 64

BASE_TO_BITS = {"A": "00", "C": "01", "G": "10", "T": "11"}

MODELED_REFERENCE_MATCH = "MODELED_REFERENCE_MATCH"
MODELED_DIFFERENCE_REVIEW = "MODELED_DIFFERENCE_REVIEW"
CLINICALLY_CONFIRMED_REMISSION = "CLINICALLY_CONFIRMED_REMISSION"
NOT_CLINICALLY_CONFIRMED = "NOT_CLINICALLY_CONFIRMED"

DISCLAIMER = (
    "Computational model only. Not a biological CRISPR intervention. "
    "A modeled reference match is not clinical remission."
)


# ---------------------------------------------------------------- hashing

def _escape(text):
    out = ['"']
    for ch in text:
        code = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif code < 0x20 or code > 0x7E:
            if code > 0xFFFF:
                code -= 0x10000
                out.append("\\u%04x\\u%04x" % (0xD800 + (code >> 10), 0xDC00 + (code & 0x3FF)))
            else:
                out.append("\\u%04x" % code)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def canonical_json(value):
    """Deterministic JSON (sorted keys, no whitespace, ASCII-only) so the
    same record hashes identically under CPython and MicroPython."""
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _escape(value)
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(canonical_json(item) for item in value) + "]"
    if isinstance(value, dict):
        parts = []
        for key in sorted(value):
            if not isinstance(key, str):
                raise TypeError("canonical_json keys must be strings")
            parts.append(_escape(key) + ":" + canonical_json(value[key]))
        return "{" + ",".join(parts) + "}"
    raise TypeError("canonical_json cannot encode " + type(value).__name__)


def sha256_hex(text):
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    return binascii.hexlify(digest).decode("ascii")


# --------------------------------------------------------------- sequences

def validate_sequence(sequence, label):
    if not isinstance(sequence, str):
        raise ValueError(label + " must be a string")
    sequence = sequence.strip().upper()
    if not sequence:
        raise ValueError(label + " is empty")
    if len(sequence) > MAX_BASES:
        raise ValueError(label + " exceeds " + str(MAX_BASES) + " bases")
    for base in sequence:
        if base not in BASE_TO_BITS:
            raise ValueError(label + " contains a non-ACGT base: " + base)
    return sequence


def to_binary(sequence):
    """A=00 C=01 G=10 T=11, space-separated per base."""
    return " ".join(BASE_TO_BITS[base] for base in sequence)


def compare(reference, observed):
    """Position-by-position substitutions (1-based). Indels are out of
    scope for this model, so lengths must match."""
    if len(reference) != len(observed):
        raise ValueError(
            "sequence lengths differ (" + str(len(reference)) + " vs "
            + str(len(observed)) + "); insertions/deletions are not modeled"
        )
    differences = []
    for index in range(len(reference)):
        if reference[index] != observed[index]:
            differences.append({
                "position": index + 1,
                "reference": reference[index],
                "observed": observed[index],
                "reference_bits": BASE_TO_BITS[reference[index]],
                "observed_bits": BASE_TO_BITS[observed[index]],
                "type": "substitution",
            })
    return differences


def identify_mutations(reference, sample):
    mutations = []
    for number, difference in enumerate(compare(reference, sample)):
        mutation = {"mutation_id": "MUT-%06d" % (number + 1)}
        mutation.update(difference)
        mutations.append(mutation)
    return mutations


def model_edit(sequence, mutations):
    """Reverse each identified substitution in the string (observed ->
    reference). Pure string transformation; see module docstring."""
    bases = list(sequence)
    edits = []
    for mutation in mutations:
        index = mutation["position"] - 1
        if bases[index] != mutation["observed"]:
            raise ValueError(mutation["mutation_id"] + " no longer matches the input sequence")
        bases[index] = mutation["reference"]
        edits.append({
            "mutation_id": mutation["mutation_id"],
            "position": mutation["position"],
            "from": mutation["observed"],
            "to": mutation["reference"],
            "from_bits": mutation["observed_bits"],
            "to_bits": mutation["reference_bits"],
        })
    return "".join(bases), edits


def verify(reference, sequence, mutations):
    differences = compare(reference, sequence)
    different_positions = [d["position"] for d in differences]
    mutation_positions = []
    for mutation in mutations:
        mutation_positions.append({
            "mutation_id": mutation["mutation_id"],
            "position": mutation["position"],
            "status": "difference" if mutation["position"] in different_positions else "match",
        })
    return {
        "total_positions": len(reference),
        "matching_positions": len(reference) - len(differences),
        "different_positions": len(differences),
        "differences": differences,
        "mutation_positions": mutation_positions,
        "binary_after": to_binary(sequence),
        "status": MODELED_REFERENCE_MATCH if not differences else MODELED_DIFFERENCE_REVIEW,
    }


# ------------------------------------------------------------------ ledger

class Ledger:
    """Hash-linked stage history. Blocks carry only the SHA-256 of each
    record; the records themselves stay off-chain."""

    def __init__(self):
        self.blocks = []
        self.records = {}

    def append(self, kind, record):
        payload_sha256 = sha256_hex(canonical_json(record))
        previous = self.blocks[-1]["block_hash"] if self.blocks else GENESIS_HASH
        header = {
            "index": len(self.blocks) + 1,
            "kind": kind,
            "payload_sha256": payload_sha256,
            "previous_hash": previous,
        }
        header["block_hash"] = sha256_hex(canonical_json(header))
        self.blocks.append(header)
        self.records[payload_sha256] = record
        return header


def verify_ledger(blocks, records=None):
    """Recompute every link (and, if records are given, every payload
    digest). Returns (ok, problems)."""
    problems = []
    previous = GENESIS_HASH
    for position, block in enumerate(blocks):
        header = {
            "index": block.get("index"),
            "kind": block.get("kind"),
            "payload_sha256": block.get("payload_sha256"),
            "previous_hash": block.get("previous_hash"),
        }
        if header["index"] != position + 1:
            problems.append("block " + str(position + 1) + ": index out of order")
        if header["previous_hash"] != previous:
            problems.append("block " + str(position + 1) + ": broken link to previous block")
        if sha256_hex(canonical_json(header)) != block.get("block_hash"):
            problems.append("block " + str(position + 1) + ": block hash mismatch")
        if records is not None:
            record = records.get(header["payload_sha256"])
            if record is None:
                problems.append("block " + str(position + 1) + ": record missing")
            elif sha256_hex(canonical_json(record)) != header["payload_sha256"]:
                problems.append("block " + str(position + 1) + ": record altered")
        previous = block.get("block_hash")
    return not problems, problems


# ---------------------------------------------------------------- workflow

def _clinical_status(evidence):
    """Clinical remission is never computed here. It is copied only from
    explicitly supplied, attributed clinical evidence."""
    if not isinstance(evidence, dict) or evidence.get("remission_confirmed") is not True:
        return {"status": NOT_CLINICALLY_CONFIRMED, "source": "none"}
    assessed_by = evidence.get("assessed_by")
    assessed_on = evidence.get("assessed_on")
    if not isinstance(assessed_by, str) or not assessed_by.strip():
        raise ValueError("clinical_evidence.assessed_by is required when remission_confirmed is true")
    if not isinstance(assessed_on, str) or not assessed_on.strip():
        raise ValueError("clinical_evidence.assessed_on is required when remission_confirmed is true")
    return {
        "status": CLINICALLY_CONFIRMED_REMISSION,
        "source": "externally_supplied",
        "assessed_by": assessed_by.strip(),
        "assessed_on": assessed_on.strip(),
    }


def _longitudinal(reference, sample, mutations, follow_ups, ledger):
    comparisons = []
    previous_sequence = None
    for number, follow_up in enumerate(follow_ups):
        if not isinstance(follow_up, dict):
            raise ValueError("each follow_up must be an object")
        label = follow_up.get("label") or ("FOLLOW-UP " + str(number + 1))
        sequence = validate_sequence(follow_up.get("sequence"), "follow_up " + str(label))
        vs_reference = compare(reference, sequence)
        original_present = [
            m["mutation_id"] for m in mutations if sequence[m["position"] - 1] == m["observed"]
        ]
        entry = {
            "label": str(label),
            "collected_on": follow_up.get("collected_on"),
            "sequence": sequence,
            "binary": to_binary(sequence),
            "differences_vs_reference": len(vs_reference),
            "differences_vs_original_sample": len(compare(sample, sequence)),
            "differences_vs_previous_follow_up": (
                None if previous_sequence is None else len(compare(previous_sequence, sequence))
            ),
            "original_mutations_present": original_present,
            "new_differences": [
                d for d in vs_reference
                if d["position"] not in [m["position"] for m in mutations]
            ],
        }
        ledger.append("FOLLOW_UP", entry)
        comparisons.append(entry)
        previous_sequence = sequence

    if not comparisons:
        trend = "NO_FOLLOW_UP_DATA"
    elif comparisons[-1]["original_mutations_present"]:
        trend = "ORIGINAL_MUTATION_DETECTED"
    elif comparisons[-1]["differences_vs_reference"] == 0:
        trend = "FOLLOW_UP_MATCHES_REFERENCE"
    else:
        trend = "FOLLOW_UP_DIFFERS_REVIEW"
    return comparisons, trend


def run(request):
    """Run the whole workflow. `request` keys:
        reference, sample            required ACGT strings, equal length
        follow_ups                   optional [{label, sequence, collected_on}]
        clinical_evidence            optional {remission_confirmed, assessed_by, assessed_on}
        case_label                   optional free-text label (avoid identifiers)
    """
    if not isinstance(request, dict):
        raise ValueError("request must be an object")
    reference = validate_sequence(request.get("reference"), "reference")
    sample = validate_sequence(request.get("sample"), "sample")
    follow_ups = request.get("follow_ups") or []
    if not isinstance(follow_ups, list) or len(follow_ups) > MAX_FOLLOW_UPS:
        raise ValueError("follow_ups must be a list of at most " + str(MAX_FOLLOW_UPS))

    ledger = Ledger()
    ledger.append("REFERENCE", {"sequence": reference, "binary": to_binary(reference)})
    ledger.append("CANCER_SAMPLE", {"sequence": sample, "binary": to_binary(sample)})

    mutations = identify_mutations(reference, sample)
    for mutation in mutations:
        ledger.append("MUTATION", mutation)

    edited, edits = model_edit(sample, mutations)
    ledger.append("CRISPR_EDIT_MODEL", {
        "input_sequence": sample,
        "edits": edits,
        "method": "string substitution model",
        "note": "not guide-RNA design, delivery or a laboratory procedure",
    })
    ledger.append("POST_EDIT", {"sequence": edited, "binary": to_binary(edited)})

    verification = verify(reference, edited, mutations)
    ledger.append("VERIFICATION", verification)

    comparisons, trend = _longitudinal(reference, sample, mutations, follow_ups, ledger)
    clinical = _clinical_status(request.get("clinical_evidence"))

    assessment = {
        "modeled_status": verification["status"],
        "longitudinal_trend": trend,
        "clinical_status": clinical,
        "research_query": {
            "topic": "CRISPR cancer",
            "mutations": [
                {"position": m["position"], "change": m["reference"] + ">" + m["observed"]}
                for m in mutations
            ],
            "sources": ["ClinicalTrials.gov", "PubMed", "Europe PMC"],
            "note": "literature/trial retrieval only; does not validate a treatment",
        },
        "disclaimer": DISCLAIMER,
    }
    ledger.append("ASSESSMENT", assessment)

    ok, problems = verify_ledger(ledger.blocks, ledger.records)
    return {
        "schema": SCHEMA,
        "case_label": request.get("case_label"),
        "before": {"sequence": sample, "binary": to_binary(sample)},
        "mutations": mutations,
        "modeled_edit": edits,
        "after": {"sequence": edited, "binary": to_binary(edited)},
        "verification": verification,
        "follow_ups": comparisons,
        "assessment": assessment,
        "ledger": {"blocks": ledger.blocks, "verified": ok, "problems": problems},
        "records": ledger.records,
    }


def main(argv):
    """Task entrypoint. The kernel passes no arguments, so the default input
    is the bundled SAMPLE.JSON; the ledger-only output (no sequences) is
    printed unless --with-records is given. `--output PATH` also writes the
    output to PATH; on the Network OS it defaults to RESULT.OUT, the
    workflow's declared output file."""
    path = "SAMPLE.JSON"
    with_records = False
    output_path = "RESULT.OUT" if sys.platform == "network-os" else None
    args = argv[1:]
    index = 0
    while index < len(args):
        arg = args[index]
        if arg == "--with-records":
            with_records = True
        elif arg == "--output" and index + 1 < len(args):
            index += 1
            output_path = args[index]
        else:
            path = arg
        index += 1
    # Read in small chunks: MicroPython preallocates the whole buffer for
    # read(n), which exhausts a small task heap.
    chunks = []
    size = 0
    with open(path, "rb") as source:
        while True:
            chunk = source.read(4096)
            if not chunk:
                break
            size += len(chunk)
            if size > MAX_INPUT_BYTES:
                raise SystemExit("input exceeds " + str(MAX_INPUT_BYTES) + " bytes")
            chunks.append(chunk)
    result = run(json.loads(b"".join(chunks).decode("utf-8")))
    if not with_records:
        result = {
            "schema": result["schema"],
            "modeled_status": result["assessment"]["modeled_status"],
            "longitudinal_trend": result["assessment"]["longitudinal_trend"],
            "clinical_status": result["assessment"]["clinical_status"]["status"],
            "mutation_count": len(result["mutations"]),
            "different_positions": result["verification"]["different_positions"],
            "ledger": result["ledger"],
            "disclaimer": DISCLAIMER,
        }
    text = canonical_json(result)
    print(text)
    if output_path is not None:
        with open(output_path, "w") as output:
            output.write(text)
    return 0 if result["ledger"]["verified"] else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
