"""
research_analysis.py
====================
Analysis half of the split research agent. research_fetch.py (host)
retrieves public records from PubMed, Europe PMC, ClinicalTrials.gov and
NIH RePORTER into RESEARCH.JSON; this file validates, de-duplicates,
scores, ranks and hashes them and writes a bounded ranking.

This single file runs in two places without changes:
  - On the host (CPython 3), imported by research_fetch.py.
  - As a Network OS MicroPython task (os/tasks/research/RESEARCH.PY,
    generated by build_task_bundles.py). The kernel's MicroPython runs one
    file with no imports of project modules and no floats, so the JSON and
    hashing helpers below are self-contained and every score is an integer.

What this is NOT: a relevance judgment or medical evidence. Scores count
query-term matches and recency; they rank literature for a human to read.
Records are public metadata only; nothing here handles patient data.
"""

import binascii
import hashlib
import json
import sys

INPUT_SCHEMA = "research-input.v1"
OUTPUT_SCHEMA = "research-ranking.v1"
MAX_INPUT_BYTES = 65536
MAX_RECORDS = 200
MAX_TERMS = 16
MAX_RANKED = 20
MAX_OUTPUT_BYTES = 16000
MAX_TITLE_CHARS = 160
TITLE_POINTS = 3
ABSTRACT_POINTS = 1
RECENT_POINTS = 1
RECENT_YEARS = 3

PUBLIC_SOURCES = ("pubmed", "europe_pmc", "clinicaltrials.gov", "nih_reporter", "clinvar")

NOTE = (
    "Ranked by query-term matches and recency for reading order only; "
    "not a relevance judgment or medical evidence."
)


# ---------------------------------------------------------------- hashing
# Same canonical form as remission_core.py (sorted keys, ASCII-only), kept
# here because kernel tasks cannot import other project files.

def _escape(text):
    out = ['"']
    for ch in text:
        code = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif code < 0x20 or code > 0x7E:
            if code > 0xFFFF:
                code -= 0x10000
                out.append("\\u%04x\\u%04x" % (0xD800 + (code >> 10), 0xDC00 + (code & 0x3FF)))
            else:
                out.append("\\u%04x" % code)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def canonical_json(value):
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _escape(value)
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(canonical_json(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{" + ",".join(
            _escape(key) + ":" + canonical_json(value[key]) for key in sorted(value)
        ) + "}"
    raise TypeError("canonical_json cannot encode " + type(value).__name__)


def sha256_hex(text):
    return binascii.hexlify(hashlib.sha256(text.encode("utf-8")).digest()).decode("ascii")


# ---------------------------------------------------------------- text
# The kernel's MicroPython implements str.strip/split/lower/isalpha/isdigit
# for ASCII only, while CPython's follow Unicode. These helpers spell the
# rules out so both runtimes give the same answer for every input:
# whitespace is exactly the set CPython's str.isspace() accepts, case
# folding and digits are ASCII, and an escaped surrogate pair counts as one
# character (CPython's json joins the pair; MicroPython's keeps two halves).

WHITESPACE = (
    "\t\n\x0b\x0c\r\x1c\x1d\x1e\x1f \x85\xa0      "
    "          　"
)


def join_surrogates(text):
    if not text or max(text) < "\ud800":
        return text
    out = []
    high = ""
    for ch in text:
        if high:
            if "\udc00" <= ch <= "\udfff":
                out.append(chr(0x10000 + ((ord(high) - 0xD800) << 10) + (ord(ch) - 0xDC00)))
                high = ""
                continue
            out.append(high)
            high = ""
        if "\ud800" <= ch <= "\udbff":
            high = ch
        else:
            out.append(ch)
    if high:
        out.append(high)
    return "".join(out)


def strip_ws(text):
    """str.strip() with CPython's whitespace set."""
    if not text or (text[0] not in WHITESPACE and text[-1] not in WHITESPACE):
        return text
    start = 0
    end = len(text)
    while start < end and text[start] in WHITESPACE:
        start += 1
    while end > start and text[end - 1] in WHITESPACE:
        end -= 1
    return text[start:end]


def words(text):
    """str.split() with no arguments, with CPython's whitespace set."""
    found = []
    word = []
    for ch in text:
        if ch in WHITESPACE:
            if word:
                found.append("".join(word))
                word = []
        else:
            word.append(ch)
    if word:
        found.append("".join(word))
    return found


def ascii_lower(text):
    """A-Z lower-cased; every other character kept as written."""
    out = []
    for ch in text:
        if "A" <= ch <= "Z":
            ch = chr(ord(ch) + 32)
        out.append(ch)
    return "".join(out)


def _word_char(ch):
    """Letters and digits for title_key: ASCII a-z and 0-9, and every other
    character outside whitespace, the Latin-1 symbols (U+0080-U+00BF, U+00D7,
    U+00F7) and the punctuation and symbol blocks U+2000-U+2BFF and
    U+3000-U+303F."""
    if ch < "\x80":
        return "a" <= ch <= "z" or "0" <= ch <= "9"
    if ch <= "\xbf" or ch == "\xd7" or ch == "\xf7" or ch == " ":
        return False
    return not (" " <= ch <= "⯿" or "　" <= ch <= "〿")


# ---------------------------------------------------------------- records

def _text(record, field, limit):
    value = record.get(field)
    if value is None:
        return ""
    if not isinstance(value, str):
        raise ValueError("record field " + field + " must be text")
    return strip_ws(join_surrogates(value))[:limit]


def validate_record(record):
    if not isinstance(record, dict):
        raise ValueError("each record must be an object")
    source = ascii_lower(_text(record, "source", 32))
    if source not in PUBLIC_SOURCES:
        raise ValueError("record source is not an allowed public source: " + source)
    classification = _text(record, "classification", 16) or "public"
    if classification != "public":
        raise ValueError("only public records can be analyzed")
    normalized = {
        "source": source,
        "external_id": _text(record, "external_id", 64),
        "title": _text(record, "title", 400),
        "abstract": _text(record, "abstract", 1000),
        "source_url": _text(record, "source_url", 300),
        "published_at": _text(record, "published_at", 32),
    }
    if not normalized["external_id"] or not normalized["title"]:
        raise ValueError("record requires external_id and title")
    return normalized


def publication_year(published_at):
    """First run of four digits (e.g. '2024 Mar 5' or '2023'), or 0."""
    digits = ""
    for ch in published_at:
        if "0" <= ch <= "9":
            digits += ch
            if len(digits) == 4:
                return int(digits)
        else:
            digits = ""
    return 0


def title_key(title):
    """Lower-case words of letters and digits, for cross-source duplicates."""
    found = []
    word = []
    for ch in ascii_lower(title):
        if _word_char(ch):
            word.append(ch)
        elif word:
            found.append("".join(word))
            word = []
    if word:
        found.append("".join(word))
    return " ".join(found)


def query_terms(request):
    terms = request.get("terms")
    if terms is None:
        query = request.get("query", "")
        if not isinstance(query, str):
            raise ValueError("query must be text")
        terms = words(join_surrogates(query))
    if not isinstance(terms, list) or len(terms) > MAX_TERMS:
        raise ValueError("terms must be a list of at most " + str(MAX_TERMS))
    cleaned = []
    for term in terms:
        if not isinstance(term, str):
            raise ValueError("each term must be text")
        term = ascii_lower(strip_ws(join_surrogates(term)))
        if term and term not in cleaned:
            cleaned.append(term)
    if not cleaned:
        raise ValueError("at least one query term is required")
    return cleaned


def score(record, terms, newest_year):
    title = ascii_lower(record["title"])
    abstract = ascii_lower(record["abstract"])
    points = 0
    matched = []
    for term in terms:
        hit = False
        if term in title:
            points += TITLE_POINTS
            hit = True
        if term in abstract:
            points += ABSTRACT_POINTS
            hit = True
        if hit:
            matched.append(term)
    year = publication_year(record["published_at"])
    if year and newest_year and newest_year - year < RECENT_YEARS:
        points += RECENT_POINTS
    return points, matched, year


def run(request):
    """Validate, de-duplicate, score, rank and hash `request` (the
    RESEARCH.JSON object written by research_fetch.py)."""
    if not isinstance(request, dict) or request.get("schema") != INPUT_SCHEMA:
        raise ValueError("input must be a " + INPUT_SCHEMA + " object")
    raw_records = request.get("records")
    if not isinstance(raw_records, list) or len(raw_records) > MAX_RECORDS:
        raise ValueError("records must be a list of at most " + str(MAX_RECORDS))
    terms = query_terms(request)

    unique = []
    by_id = {}
    by_title = {}
    for raw in raw_records:
        record = validate_record(raw)
        record["record_sha256"] = sha256_hex(canonical_json(record))
        id_key = record["source"] + ":" + record["external_id"]
        key = title_key(record["title"])
        existing = by_id.get(id_key)
        if existing is None and key:
            existing = by_title.get(key)
        if existing is not None:
            if record["source"] not in existing["also_in"] and record["source"] != existing["source"]:
                existing["also_in"].append(record["source"])
            continue
        record["also_in"] = []
        by_id[id_key] = record
        if key:
            by_title[key] = record
        unique.append(record)

    newest_year = 0
    for record in unique:
        newest_year = max(newest_year, publication_year(record["published_at"]))
    for record in unique:
        points, matched, year = score(record, terms, newest_year)
        record["score"] = points
        record["matched_terms"] = matched
        record["year"] = year
    ordered = sorted(
        unique,
        key=lambda r: (-r["score"], -r["year"], r["source"], r["external_id"]),
    )

    ranked = []
    for position, record in enumerate(ordered[:MAX_RANKED]):
        ranked.append({
            "rank": position + 1,
            "source": record["source"],
            "external_id": record["external_id"],
            "title": record["title"][:MAX_TITLE_CHARS],
            "source_url": record["source_url"],
            "published_at": record["published_at"],
            "score": record["score"],
            "matched_terms": record["matched_terms"],
            "also_in": record["also_in"],
            "record_sha256": record["record_sha256"],
        })
    result = {
        "schema": OUTPUT_SCHEMA,
        "query": request.get("query", ""),
        "terms": terms,
        "input_records": len(raw_records),
        "unique_records": len(unique),
        "duplicates_removed": len(raw_records) - len(unique),
        "ranked": ranked,
        "all_records_sha256": sha256_hex(
            canonical_json([record["record_sha256"] for record in unique])
        ),
        "note": NOTE,
    }
    # Kernel tasks may write at most 16 KiB per output file.
    while len(canonical_json(result)) > MAX_OUTPUT_BYTES and result["ranked"]:
        result["ranked"] = result["ranked"][:-1]
    return result


def main(argv):
    """Task entrypoint. Reads RESEARCH.JSON (or the first argument) and
    prints the ranking; `--output PATH` also writes it, defaulting to
    RANKED.OUT (the workflow's declared output) on the Network OS."""
    path = "RESEARCH.JSON"
    output_path = "RANKED.OUT" if sys.platform == "network-os" else None
    args = argv[1:]
    index = 0
    while index < len(args):
        if args[index] == "--output" and index + 1 < len(args):
            index += 1
            output_path = args[index]
        else:
            path = args[index]
        index += 1
    with open(path, "rb") as source:
        raw = source.read()
    if len(raw) > MAX_INPUT_BYTES:
        raise SystemExit("input exceeds " + str(MAX_INPUT_BYTES) + " bytes")
    result = run(json.loads(raw.decode("utf-8")))
    text = canonical_json(result)
    print(text)
    if output_path is not None:
        with open(output_path, "w") as output:
            output.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
