[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
bootloader_api = "0.11.12"
linked_list_allocator = { version = "0.10.5", default-features = false }
smoltcp = { version = "0.14.0", default-features = false, features = [
    "medium-ethernet",
    "iface-max-addr-count-4",
    "proto-ipv4",
    "proto-ipv6",
    "proto-ipv6-slaac",
    "socket-dhcpv4",
    "socket-icmp",
    "socket-tcp",
    "socket-udp",
] }
